### ISSUE TITLE
brenda.txt

### ISSUE THREAD

**Issue by bozhenhhu** [SizheQiu/DLTKcat#1]
Hi, @SizheQiu 

Thanks for your great work, I want to know where could I get the file brenda.txt mentioned in the file GetData.ipynb?

**Comment by SizheQiu** [comment]
You can download that from the website Brenda Enzyme database. that file is
quite large so I did not upload it to GitHub.

Bozhen Hu ***@***.***>于2024年5月6日 周一02:47写道：

**Comment by SizheQiu** [comment]
btw, can you send an email to my email adress that I post on my profile ? I cannot find your contact.

**Comment by bozhenhhu** [comment]
Hi, Sizhe,


Thanks for your great work and reply.  I have found that file from the website of the Brenda Enzyme database. Recently, I have been interested in the prediction of enzyme kinetic parameters. This is my email, and I may have a few more follow-up questions. Thanks for your help.

Kind Regards,
Bozhen.
________________________________
发件人: Sizhe Qiu ***@***.***>
发送时间: 2024年5月6日 19:40
收件人: SizheQiu/DLTKcat ***@***.***>
抄送: Bozhen HU 胡博振 ***@***.***>; Author ***@***.***>
主题: Re: [SizheQiu/DLTKcat] brenda.txt (Issue #1)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

btw, can you send an email to my email adress that I post on my profile ? I cannot find your contact.

―

**Comment by SizheQiu** [comment]
can you send direcly to my adress? your email adress is encrypted if you send via github.

**Comment by bozhenhhu** [comment]
Hi,

Sorry for inconvenience.

This is my email, ***@***.***


Kind Regards,
Bozhen.
________________________________
发件人: Sizhe Qiu ***@***.***>
发送时间: 2024年5月6日 20:07
收件人: SizheQiu/DLTKcat ***@***.***>
抄送: Bozhen HU 胡博振 ***@***.***>; Author ***@***.***>
主题: Re: [SizheQiu/DLTKcat] brenda.txt (Issue #1)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

can you send direcly to my adress? your email adress is encrypted if you send via github.

―

**Comment by SizheQiu** [comment]
Hi, you can find my email contact from the paper or my github page (contact section).
As long as you reply through github, the email adress will be encrypted as "***@****".
