### ISSUE TITLE
Some SMILES from E.coli dataset can not be correctly processed.

### ISSUE THREAD

**Issue by Phuangji** [SizheQiu/DLTKcat#2]
Hello!
    When I predict kcat of some E.coli reactions, it says my SMILES are out of the range of atoms like this.
    For example, CC1(CC(=O)O)C2=Cc3[nH]c(c(CCC(=O)O)c3CC(=O)O)Cc3[nH]c(c(CC(=O)O)c3CCC(=O)O)C=C3N=C(C=C(N2)C1CCC(=O)O)C(C)(CC(=O)O)C3CCC(=O)O
```
Traceback (most recent call last):
  File "predict.py", line 82, in <module>
    pred = M( atoms_pad, atoms_mask, adjacencies_pad, amino_pad, amino_mask, batch_fps, inv_Temp, Temp )
  File "/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/DLTKcat/code/DLTKcat.py", line 161, in forward
    atoms_vector = self.comp_gat(atoms, adjacency)
  File "/DLTKcat/code/DLTKcat.py", line 102, in comp_gat
    atoms_vector = self.embedding_layer_atom(atoms)
  File "/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/torch/nn/modules/sparse.py", line 162, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
I use CPU here. If use GPU there will be similar errors. 
Could you please tell me what's the problem with my operation?
Looking forward to your reply. 
Thank you!

**Comment by SizheQiu** [comment]
I think the "[nH]" in the SMILES string is the issue. In the training dataset I used, all SMILES strings were canonical SMILES, and those with ions were all filtered out. Please make sure the SMILES string of the substrate was in canonical form.

**Comment by Phuangji** [comment]
Thank you for your reply.
There are still some questions.
First, I did convert my SMILES to canonical forms , and the code is as follows:
```
class MolClean(object):
    def __init__(self):
        self.normizer = MolStandardize.normalize.Normalizer()
        self.lfc = MolStandardize.fragment.LargestFragmentChooser()
        self.uc = MolStandardize.charge.Uncharger()
 
    def clean(self, smi):
        mol = Chem.MolFromSmiles(smi)
        if mol:
            mol = self.normizer.normalize(mol)
            mol = self.lfc.choose(mol)
            mol = self.uc.uncharge(mol)
            smi = Chem.MolToSmiles(mol,  isomericSmiles=False, canonical=True)
            return smi
        else:
            return None
```
Second, I can normally handle some SMILES that contain [nH], such as:
O=c1[nH]c(=O)c2[nH]cnc2[nH]1
Also, the error SMILES does not have ions , it only contains a nitrogen heterocycle.
So maybe your reply does not solve my problem.
Thank you again!

**Comment by SizheQiu** [comment]
Ok, in this case, the most possible reason is that the substrate contains some molecular fingerprints that are not in my training data, and thus the substrate cannot be encoded as features.

**Comment by liangzais** [comment]
I have also faced a similar problem. Is there a solution to this problem? Looking forward to your reply！

**Comment by liangzais** [comment]
I cannot incorporate my data into training or prediction.
![2c62ace9df6cfe786a396c6e119d788](https://github.com/user-attachments/assets/5b934b31-b8e7-4bec-9222-838cd9026382)

**Comment by Phuangji** [comment]
Maybe you could skip the unsuccessful data or retrain the model with your own data.

**Comment by SizheQiu** [comment]
This issue is caused by the embedding method of molecule and protein sequence. Unfortunately, DLTKcat cannot predict kcat for substrates with molecular fingerprints not included in the training dataset.

**Comment by Phuangji** [comment]
Hi, 
When I use a new dataset to train DLTKcat, I found that the model training effect fluctuated greatly, R2 fluctuated from 0.2 to 0.5, did you encounter this problem in your previous training? I use the param_2.pkl as the hyperparam, and the training and test dataset remains the same for every training process. 

> This issue is caused by the embedding method of molecule and protein sequence. Unfortunately, DLTKcat cannot predict kcat for substrates with molecular fingerprints not included in the training dataset.

**Comment by SizheQiu** [comment]
If you fix the random seed using `np.random.seed(seed), random.seed(seed), torch.manual_seed(seed)`, the training performance will be fixed.

**Comment by Phuangji** [comment]
OK, thanks for your kind reply.
